### ISSUE TITLE
DBLOG and backinstantiation

### ISSUE THREAD

**Issue by davidenitti** [BayesianLogic/blog#339]
In the DBLOG workshop poster a method to avoid backinstantiation is mentioned.
Can I try this in the code?

**Comment by jxwuyi** [comment]
Which poster? What did you mean by backinstantiation?

**Comment by davidenitti** [comment]
this poster http://www.ai.sri.com/~braz/papers/nips08.ppt
The backinstantiation is explained in the poster.

**Comment by jxwuyi** [comment]
I see. Here is a misunderstanding I have to explain. For a random variable, for example the random variable Maze(1,1) (without time step), there are only *ONE* Maze(1,1) always. If you define Maze() by Maze(x,y,timestep t), then there will be infinitely many random variables, Maze(1,1,@0), Maze(1,1,@1), Maze(1,1,@2)..... 
They are different concepts. If you include timestep in the arguments, then this variable becomes temporal variables. For temporal variables, whenever timestep increases by 1, we will create a new variable with the latest timestep and remove the variable with older timestep. For static variable, we will neither create a new one nor remove an old one. Instead, we will always keep that in the corresponding particle. When we duplicate particles in the resample step, we will also duplicate all the included static variables. As long as a static variable is sampled, the value of it will never be changed.

It is a standard feature of particle filtering. It is already there.

**Comment by jxwuyi** [comment]
If you would like to define temporal Maze(), you should include timestep in the arguments, for example Maze(x,y,timestep t).
However, I have to say if you really want it dynamic, due to current implementation issue of BLOG, you have to ensure that at each timestep all the possible positions of Maze(x,y) are sampled.
Note that we only keep information of the latest timestep. For example, if you did not sample Maze(x,y,@2) but you did sample Maze(x,y,@4) while Maze(x,y,@4) somehow depends on Maze(x,y,@2), then a problem occurs since all the random variables for timestep @2 have been removed.
In order to overcome that, at the current stage, the only way is to query that variable to ensure that it is sampled in every timestep. 
For example
you can query Maze(1,1,@0), Maze(1,1,@1), Maze(1,1,@2), Maze(1,1,@3) .....

Well, it is for now the only solution. I know it is a little bit annoying. This is due to some implementation issue. We might propose a better solution in the near future.
